pipeline {
    agent any

    stages {
        stage('Scan image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'sysdig-secure-api-credentials', passwordVariable: 'SECURE_API_TOKEN', usernameVariable: '')]) {
                    sh '''
                        VERSION=$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)
                        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/${VERSION}/linux/amd64/sysdig-cli-scanner"
                        chmod +x ./sysdig-cli-scanner
                        ./sysdig-cli-scanner --apiurl https://secure.sysdig.com mongo-express:0.54.0
                    '''
                }
            }
        }
    }
}
