pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1 
kind: Pod 
metadata: 
    name: inline-scan-worker
spec: 
    containers: 
      - name: jnlp
      - name: inline-scan
        image: sysdiglabs/secure-inline-scan:2
        command: ['cat']
        tty: true
"""
       }
   }

    parameters { 
        string(name: 'IMAGE_NAME', defaultValue: 'sysdiglabs/dummy-vuln-app', description: 'Name of the image to be built andscanned (e.g.: myrepo/dummy-app)') 
    }
    
    environment {
        SECURE_API_KEY = credentials('sysdig-secure-api-credentials')
    }
    
    stages {
        stage('Scanning Image pulled from repository') {
            steps {
                container("inline-scan") {
                    sh "/sysdig-inline-scan.sh -k ${SECURE_API_KEY_PSW} ${IMAGE_NAME}"
                }
            }
        }
   }
}