steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_URL}:${_IMAGE_TAG}', '.']

- name: 'quay.io/sysdig/secure-inline-scan:2'
  args: [ '--storage-type=docker-daemon', '--storage-path=/var/run/docker.sock', '${_IMAGE_URL}:${_IMAGE_TAG}' ]
  secretEnv: ['SYSDIG_API_TOKEN']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_URL}:${_IMAGE_TAG}']

availableSecrets:
  secretManager:
  - versionName: projects/PROJECT_ID/secrets/sysdig_token/versions/latest
    env: 'SYSDIG_API_TOKEN'

substitutions:
  _IMAGE_URL: 'gcr.io/project-name/image-name'
  _IMAGE_TAG: 'latest'

timeout: 900s
