all:
	GOOS=darwin GOARCH=amd64 go build -o sysdigv1beta_to_sarif-darwin-amd64 sysdigv1beta_to_sarif.go
	GOOS=darwin GOARCH=arm64 go build -o sysdigv1beta_to_sarif-darwin-arm64 sysdigv1beta_to_sarif.go
	GOOS=linux GOARCH=amd64 go build -o sysdigv1beta_to_sarif-linux-amd64 sysdigv1beta_to_sarif.go
	GOOS=linux GOARCH=arm64 go build -o sysdigv1beta_to_sarif-linux-arm64 sysdigv1beta_to_sarif.go
	GOOS=darwin GOARCH=amd64 go build -o sysdigv1_to_sarif-darwin-amd64 sysdigv1_to_sarif.go
	GOOS=darwin GOARCH=arm64 go build -o sysdigv1_to_sarif-darwin-arm64 sysdigv1_to_sarif.go
	GOOS=linux GOARCH=amd64 go build -o sysdigv1_to_sarif-linux-amd64 sysdigv1_to_sarif.go
	GOOS=linux GOARCH=arm64 go build -o sysdigv1_to_sarif-linux-arm64 sysdigv1_to_sarif.go
