all:
	GOOS=darwin GOARCH=amd64 go build -o sysdig2sarif-darwin-amd64 sysdig2sarif.go
	GOOS=darwin GOARCH=arm64 go build -o sysdig2sarif-darwin-arm64 sysdig2sarif.go
	GOOS=linux GOARCH=amd64 go build -o sysdig2sarif-linux-amd64 sysdig2sarif.go
	GOOS=linux GOARCH=arm64 go build -o sysdig2sarif-linux-arm64 sysdig2sarif.go
