pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
    name: inline-scan-worker
spec:
    containers:
      - name: jnlp
        workingDir: /tmp
        volumeMounts:
        # Mount the Openshift SA dockercfg secret as .dockercfg
        - mountPath: /tmp/.dockercfg
          name: sa-dockercfg
          subPath: .dockercfg
      - name: maven
        image: maven:3.6-jdk-11
        command: ['cat']
        tty: true
        workingDir: /tmp
      - name: builder
        image: gcr.io/kaniko-project/executor:debug
        command: ['cat']
        tty: true
        workingDir: /tmp
        env:
        - name: DOCKER_CONFIG
          value: /tmp
      - name: inline-scan-option1-with-configjson
        image: quay.io/sysdig/secure-inline-scan:2
        command: ['cat']
        tty: true
        workingDir: /tmp
      - name: inline-scan-option2-with-dockercfg
        image: quay.io/sysdig/secure-inline-scan:2
        command: ['cat']
        tty: true
        workingDir: /tmp
        volumeMounts:
        # Mount the Openshift SA dockercfg secret as .dockercfg
        - mountPath: /tmp/.dockercfg
          name: sa-dockercfg
          subPath: .dockercfg
    volumes:
    - name: sa-dockercfg
      secret:
        defaultMode: 420
        # Name of the secret in Kubernetes used by the Service Account
        # Requires push and pull access to the internal registry.
        # See https://docs.openshift.com/container-platform/4.6/registry/accessing-the-registry.html
        secretName: builder-dockercfg-r2gc4
"""
       }
   }

    parameters {
        string(name: 'IMAGE_NAME', defaultValue: 'image-registry.openshift-image-registry.svc.cluster.local:5000/default/test-maven-app', description: 'Name of the image to be built andscanned (e.g.: myrepo/dummy-app)')
    }

    environment {
        SECURE_API_KEY = credentials('sysdig-secure')
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/openshift/test-maven-app'
            }
        }

        stage('Prepare internal registry credentials') {
            steps {
                // We need to convert old .dockercfg format to config.json wrapping in "auth" field for Kaniko
                sh "echo -n \"{ \\\"auths\\\": \"  > /tmp/config.json"
                sh "cat /tmp/.dockercfg >> /tmp/config.json"
                sh "echo \"}\" >>/tmp/config.json"
            }
        }

        stage('Build app') {
            steps {
                container("maven") {
                    sh "mvn package"
                }
            }
        }

        stage('Build image and push') {
            steps {
                container("builder") {
                    sh """cat > Dockerfile <<EOF
FROM gcr.io/distroless/java:11
COPY target/hello.jar /hello.jar
CMD /hello.jar
EOF
                    """
                    sh "/kaniko/executor --context . --destination ${IMAGE_NAME} --skip-tls-verify"
                }
            }
        }

        stage('Option 1: Scanning Image pulled from repository using config.json format') {
            steps {
                container("inline-scan-option1-with-configjson") {
                    sh "id"
                    sh "/sysdig-inline-scan.sh -k ${SECURE_API_KEY_PSW} --registry-skip-tls --registry-auth-file /tmp/config.json ${IMAGE_NAME}"
                }
            }
        }

        stage('Option 2: Scanning Image pulled from repository using .dockercfg format') {
            steps {
                container("inline-scan-option2-with-dockercfg") {
                    sh "id"
                    // Instead of using --registry-auth-file, we can just provide the .dockercfg file at /tmp/sysdyg-inline-scan/home/.dockercfg
                    sh "mkdir -p /tmp/sysdig-inline-scan/home"
                    sh "cp /tmp/.dockercfg /tmp/sysdig-inline-scan/home"
                    sh "/sysdig-inline-scan.sh -k ${SECURE_API_KEY_PSW} --registry-skip-tls ${IMAGE_NAME}"
                }
            }
        }
   }
}
